# -*- coding: utf-8 -*-
"""GaussSeidel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1et-Qn1ExdMsZmtWH4XkpGOZeqWqiW-5h
"""

import numpy as np
from numpy.linalg import inv

def GaussSeidel(A,b,tol,numIter):
  n = np.size(A,0)
  L = - np.tril(A, -1)
  U = - np.triu(A,1)
  D = A+L+U
  x0 = np.zeros([n,1])
  Tg = np.matmul(inv(D-L),U)
  autoval, autovec = np.linalg.eig(Tg)
  autoval = abs(autoval)

  for lam in autoval:
    if lam >= 1:
      return ("El método no pudo converger de acuerdo a los parametros ingresados")

  C = np.matmul(inv(D-L),b)
  xn = (np.matmul(Tg,x0))+C
  error = np.array(abs(xn - (np.dot(Tg,xn)+C)))
  error = np.amax(error)
  iter = 0
  while ((error > tol) and (iter<numIter)):
    nuevo = np.matmul(Tg,xn)+C
    error = np.array(abs(nuevo-xn))
    error = np.amax(error)
    xn = nuevo
    iter = iter +1
  return("El método converge en "+str(xn))

#A = np.array([[3,-1,1],[1,-8,-2],[1,1,5]])
#b = np.array([[-2],[1],[4]])
#tol = 10^(-5)
#numIter = 20
#GaussSeidel(A,b,tol,numIter)