# -*- coding: utf-8 -*-
"""Interpolacion Lagrange.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1et-Qn1ExdMsZmtWH4XkpGOZeqWqiW-5h
"""

#Interpolación Lagrange
import sympy as sym
import numpy as np
x = sym.Symbol("x")
def lagrange(puntos):
  n = np.size(puntos,0)
  p = 0
  X = puntos[:,0]
  Y = puntos[:,1]
  for k in range(n):
    L=1
    for i in range(n):
      if i != k:
        L = L*((x-X[i])/(X[k]-X[i]))
    p = p +L*(Y[k])
  p = sym.simplify(sym.expand(p))
  return p

#puntos = np.array([[-2,12.135],[-1,6.368],[2,-4.611],[3,2.086]])
#lagrange(puntos)