# -*- coding: utf-8 -*-
"""Punto fijo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1et-Qn1ExdMsZmtWH4XkpGOZeqWqiW-5h
"""

#Método de punto fijo (Método abierto)

import sympy as sym
from math import e
from math import sqrt
x = sym.Symbol('x')

def puntoFijo(f,x0,numIter, tol):
  g= -(f-x)
  iter = 0
  error = tol + 1
  while (iter < numIter and error > tol):
    xn = float(g.subs(x,x0))
    error = abs(xn - x0)
    iter += 1
    x0 = xn
  if error <= tol:
    return(str(xn) + " es raíz con tolerancia de " + str(tol))
  else:
    return("El método no converge")

#f = x**3 + 2*x**2 - x -1
#puntoFijo(f, 1, 100, 0.00001)